import Mathlib.Analysis.Distribution.SchwartzSpace.Deriv

/-!
# Chapter 6 — Test Functions and Distributions

Rudin, *Functional Analysis* (2nd ed.), Chapter 6.

Note: Rudin develops $\mathcal{D}(\Omega)$ — compactly-supported smooth
test functions — and their dual $\mathcal{D}'(\Omega)$. mathlib currently
provides the closely related Schwartz space $\mathcal{S}$ and its dual
space of *tempered* distributions (Rudin Ch 7). Until $\mathcal{D}(\Omega)$
lands upstream we use the Schwartz-space analogue here.
-/

namespace Rudin.Ch06

open SchwartzMap

section SchwartzSpace

variable (𝕜 : Type*) [RCLike 𝕜]
variable (E : Type*) [NormedAddCommGroup E] [NormedSpace ℝ E]
variable (F : Type*) [NormedAddCommGroup F] [NormedSpace ℝ F] [NormedSpace 𝕜 F]
  [SMulCommClass ℝ 𝕜 F]

/-- **Schwartz space** — rapidly decreasing smooth functions `E → F`,
with the Fréchet topology generated by the seminorms
`‖x‖^k ‖f^{(n)}(x)‖`. (Rudin 7.3; included in Ch 6 here as the main
"test-function" space available in mathlib.) -/
abbrev Schwartz : Type _ := 𝓢(E, F)

/-- **Theorem 6.4 (differentiation is continuous on test functions)** —
The Fréchet derivative gives a continuous linear map
`𝓢(E, F) → 𝓢(E, E →L[ℝ] F)`. -/
noncomputable def fderivSchwartz : 𝓢(E, F) →L[𝕜] 𝓢(E, E →L[ℝ] F) :=
  SchwartzMap.fderivCLM 𝕜 E F

end SchwartzSpace

end Rudin.Ch06
